"""Fabricated UNA controller activity for the README screenshot.

All names, sites, devices, users, and addresses in this fixture are invented.
The screenshot version is deliberately not stored here: the generator reads it
from the application source each time it runs.
"""

META = {
    "tz": "CDT",
    "time_ranges": ["1 Hour", "1 Day", "1 Week", "1 Month"],
    "default_time_range": "1 Day",
    "log_types": ["General", "Audit"],
    "default_log_type": "General",
    "categories": [
        "Client Devices",
        "Internet and WAN",
        "Power",
        "Security",
        "Software Updates",
        "UniFi Devices",
        "UniFi Ethernet Ports",
        "VPN",
    ],
    "events": [
        "WiFi Client Connected",
        "WiFi Client Disconnected",
        "WiFi Client Roamed",
        "Wired Client Connected",
        "Wired Client Disconnected",
    ],
    "site": {"id": "site-northwind", "label": "Northwind Lab (.example)"},
    "controller_url": "https://una-gateway.example",
    "user": "log.viewer",
}

ROWS = [
    {
        "datetime": "2026-08-12 14:42:18 CDT",
        "datetime_raw": 1786563738000,
        "site": "Northwind Lab",
        "category": "Client Devices",
        "event": "WiFi Client Connected",
        "severity": "INFO",
        "description": "laptop-avery joined Staff-WiFi from 10.44.18.57",
        "client": "laptop-avery",
        "mac": "02:6A:44:18:57:01",
    },
    {
        "datetime": "2026-08-12 14:38:51 CDT",
        "datetime_raw": 1786563531000,
        "site": "Northwind Lab",
        "category": "Client Devices",
        "event": "WiFi Client Roamed",
        "severity": "LOW",
        "description": "avery-lt roamed from Lab-AP-01 to Lab-AP-03",
        "client": "avery-lt",
        "mac": "02:6A:44:22:14:02",
    },
    {
        "datetime": "2026-08-12 14:31:09 CDT",
        "datetime_raw": 1786563069000,
        "site": "Northwind Lab",
        "category": "UniFi Ethernet Ports",
        "event": "Wired Client Disconnected",
        "severity": "MEDIUM",
        "description": "label-printer-02 disconnected from switch-lab-03 port 18",
        "client": "label-printer-02",
        "mac": "02:6A:44:18:23:03",
    },
    {
        "datetime": "2026-08-12 14:26:44 CDT",
        "datetime_raw": 1786562804000,
        "site": "Northwind Lab",
        "category": "Client Devices",
        "event": "WiFi Client Connected",
        "severity": "INFO",
        "description": "tablet-ops-04 joined Staff-WiFi from 10.44.18.64",
        "client": "tablet-ops-04",
        "mac": "02:6A:44:18:42:04",
    },
    {
        "datetime": "2026-08-12 14:19:27 CDT",
        "datetime_raw": 1786562367000,
        "site": "Northwind Lab",
        "category": "Client Devices",
        "event": "WiFi Client Disconnected",
        "severity": "INFO",
        "description": "tablet-ops-04 left Staff-WiFi after 02:17:33 online",
        "client": "tablet-ops-04",
        "mac": "02:6A:44:18:64:05",
    },
    {
        "datetime": "2026-08-12 14:12:06 CDT",
        "datetime_raw": 1786561926000,
        "site": "Northwind Lab",
        "category": "UniFi Ethernet Ports",
        "event": "Wired Client Connected",
        "severity": "INFO",
        "description": "workstation-nora connected to switch-lab-02 port 11",
        "client": "workstation-nora",
        "mac": "02:6A:44:18:71:06",
    },
    {
        "datetime": "2026-08-12 14:04:35 CDT",
        "datetime_raw": 1786561475000,
        "site": "Northwind Lab",
        "category": "Client Devices",
        "event": "WiFi Client Connected",
        "severity": "INFO",
        "description": "scanner-receiving joined Warehouse-WiFi from 10.44.19.88",
        "client": "scanner-receiving",
        "mac": "02:6A:44:19:88:07",
    },
    {
        "datetime": "2026-08-12 13:57:42 CDT",
        "datetime_raw": 1786561062000,
        "site": "Northwind Lab",
        "category": "Client Devices",
        "event": "WiFi Client Roamed",
        "severity": "LOW",
        "description": "handheld-07 roamed from Lab-AP-02 to Lab-AP-04",
        "client": "handheld-07",
        "mac": "02:6A:44:19:07:08",
    },
    {
        "datetime": "2026-08-12 13:49:18 CDT",
        "datetime_raw": 1786560558000,
        "site": "Northwind Lab",
        "category": "UniFi Ethernet Ports",
        "event": "Wired Client Disconnected",
        "severity": "HIGH",
        "description": "camera-loading-01 disconnected from switch-lab-01 port 7",
        "client": "camera-loading-01",
        "mac": "02:6A:44:19:01:09",
    },
    {
        "datetime": "2026-08-12 13:41:53 CDT",
        "datetime_raw": 1786560113000,
        "site": "Northwind Lab",
        "category": "UniFi Ethernet Ports",
        "event": "Wired Client Connected",
        "severity": "INFO",
        "description": "meeting-room-panel connected to switch-lab-02 port 22",
        "client": "meeting-room-panel",
        "mac": "02:6A:44:19:22:10",
    },
    {
        "datetime": "2026-08-12 13:35:20 CDT",
        "datetime_raw": 1786559720000,
        "site": "Northwind Lab",
        "category": "Client Devices",
        "event": "WiFi Client Disconnected",
        "severity": "LOW",
        "description": "guest-tablet-03 left Guest-WiFi after 00:36:11 online",
        "client": "guest-tablet-03",
        "mac": "02:6A:44:19:03:11",
    },
    {
        "datetime": "2026-08-12 13:28:04 CDT",
        "datetime_raw": 1786559284000,
        "site": "Northwind Lab",
        "category": "Client Devices",
        "event": "WiFi Client Connected",
        "severity": "INFO",
        "description": "phone-riley joined Staff-WiFi from 10.44.18.91",
        "client": "phone-riley",
        "mac": "02:6A:44:18:91:12",
    },
    {
        "datetime": "2026-08-12 13:20:37 CDT",
        "datetime_raw": 1786558837000,
        "site": "Northwind Lab",
        "category": "UniFi Ethernet Ports",
        "event": "Wired Client Disconnected",
        "severity": "MEDIUM",
        "description": "access-control-02 disconnected from switch-lab-03 port 4",
        "client": "access-control-02",
        "mac": "02:6A:44:18:04:13",
    },
]
