name: Release
on:
  push:
    tags: ['v*']
jobs:
  release:
    uses: JDE-Projects/Build-Tools/.github/workflows/release.yml@a2cb83a9459b6c357fc4f7778e8d1e99844fc8f9 # Build-Tools main (checkout v7)
    permissions:
      id-token: write
      attestations: write
      contents: write
    with:
      app_name: SimpleUNALogViewer
      dist_subfolder: "Simple UNA Log Viewer"
      python_version: "3.14"
      build_command: "Build_Simple_UNA_Log_Viewer.bat"
      app_id: "0c8c994c-416a-4eca-8c6b-3ac1351afea3"
